### ISSUE TITLE
版本更新预备

### ISSUE THREAD

**Issue by hiroi-sora** [jerrylususu/PaddleOCR-json-java-api#3]
Hello，新版本准备发布，请稍微修改下API~

必须修改的内容：

- 启动时传入 `use_debug=0` 参数以关闭debug模式。替代原来的 `--use_system_pause=0`
- 状态码的更新。（我建议只识别100和101就行了，其他状态码原样传给调用方）

可选的更新内容：

- 为剪贴板识图多封装一层接口，路径传入 `clipboard` 即可。
- 添加一个手动结束子进程的接口。（如果已有请无视）
- 另外你的README可以添加到源项目 api/java 目录下

具体更新内容可以看 [dev](https://github.com/hiroi-sora/PaddleOCR-json/tree/dev) 分支下的README及 /docs 下的文档。

搞定请推回我的dev分支，谢谢~

**Comment by hiroi-sora** [comment]
以及这是新版本的程序。只含exe文件，请扔到旧版本的目录下
[PaddleOCR_json v1.2.1.zip](https://github.com/PunchlY/PaddleOCR-json-node-api/files/9630363/PaddleOCR_json.v1.2.1.zip)

另外，新版本的启动参数不再支持中文；如果要传入配置文件路径、模型库路径等，必须全ascii。

**Comment by jerrylususu** [comment]
变更记录：
- 启动时传入 use_debug=0 参数
- 状态码只判断 100 和 101
- 增加了识别剪贴板接口 `runOcrOnClipboard`
- 传入参数如果存在非 ASCII 字符时抛出异常

其他说明
- 手动结束子进程：现在 `Ocr` 类使用 Java 的 `try-with-resources` 模式实现，直接调用 `ocr.close()` 即可结束子进程
